### ISSUE TITLE
No such file or directory @ rb_sysopen - name=buspirate

### ISSUE THREAD

**Issue by sabas1080** [mchck/programmer#11]
Hi

I have the next error with Bus Pirate and flash.rb

```
ruby -I. flash.rb name=buspirate:dev=/dev/ttyUSB0
flash.rb:26:in `read': No such file or directory @ rb_sysopen - name=buspirate:dev=/dev/ttyUSB0 (Errno::ENOENT)
	from flash.rb:26:in `readbins'
	from flash.rb:36:in `<main>'
```

Thanks

**Comment by sabas1080** [comment]
Solution:

`ruby -I. flash.rb --adapter=buspirate,dev=/dev/ttyUSB0 test.bin 0x00000000`

Thanks
